### ISSUE TITLE
meu email, não sei se irei deletar depois

### ISSUE THREAD

**Issue by demon-cerbero** [ashuradev/ignitor#13]
fabio.ventao@gmail.com

**Comment by ashuradev** [comment]
meu e-mail tmb: the.lucas2016@gmail.com

**Comment by demon-cerbero** [comment]
Me chama no icq

Em sáb, 11 de jul de 2020 16:26, ashuradev <notifications@github.com>
escreveu:

**Comment by demon-cerbero** [comment]
neo_evil

Em sáb, 11 de jul de 2020 16:26, ashuradev <notifications@github.com>
escreveu:

**Comment by ashuradev** [comment]
oq é icq?

**Comment by demon-cerbero** [comment]
Pesquise

Em sáb, 11 de jul de 2020 17:34, ashuradev <notifications@github.com>
escreveu:

**Comment by ashuradev** [comment]
puts n consigo entrar precisa de numero de telefone bora pro jabber?

**Comment by ashuradev** [comment]
n tenho celular

**Comment by demon-cerbero** [comment]
E instagram?

Em sáb, 11 de jul de 2020 17:44, ashuradev <notifications@github.com>
escreveu:

**Comment by ashuradev** [comment]
https://instagram.com/ikuzikuyashurinhacorno

**Comment by ashuradev** [comment]
ae
eu excluir meu discord kk

**Comment by demon-cerbero** [comment]
Pqp rsrs

Em sex, 7 de ago de 2020 20:00, Ashura <notifications@github.com> escreveu:

**Comment by demon-cerbero** [comment]
Hoje to ocupado numa recepção burrifando alcool

Em sex, 7 de ago de 2020 20:03, Ninguém no-name <fabio.ventao@gmail.com>
escreveu:

**Comment by ashuradev** [comment]
rtrelçttkw

**Comment by ashuradev** [comment]
agr por onde iremos nos contatar?

**Comment by ashuradev** [comment]
ja ouviu falar do jabber/dino?

**Comment by demon-cerbero** [comment]
Não mano a gente pode pelo discord

Em sex, 7 de ago de 2020 20:17, Ashura <notifications@github.com> escreveu:

**Comment by ashuradev** [comment]
no caso eu excluir o discord por um motivo
ent n posso kk
tenta v o jabber ai
mt bom

**Comment by demon-cerbero** [comment]
Ok... Quando fizer te aviso

Em sex, 7 de ago de 2020 20:27, Ashura <notifications@github.com> escreveu:

**Comment by ashuradev** [comment]
blz vo mandar o link: dino.im

**Comment by ashuradev** [comment]
ele é mt bom e criptografado

**Comment by ashuradev** [comment]
qnd pedir pra colocar um servidor coloca: jabber.ccc.de

**Comment by ashuradev** [comment]
no caso meu nick vo enviar pro seu email

**Comment by ashuradev** [comment]
consegiu?

**Comment by ashuradev** [comment]
na vdd o dino é so pra linux kk
instala o pidgin

**Comment by demon-cerbero** [comment]
baixar pidgin pra usar outras contas nele?
não faz sentido...

Em sáb., 8 de ago. de 2020 às 15:02, Ashura <notifications@github.com>
escreveu:

**Comment by demon-cerbero** [comment]
Mano bora conversar pelo hangout, tem pra celular, ou web...
manda uma solicitação para fabio.ventao@gmail.com

Em sáb., 8 de ago. de 2020 às 15:02, Ashura <notifications@github.com>
escreveu:

**Comment by ashuradev** [comment]
eu criei um novo discord: ikuzikuyaruhsa#6860
adiciona logo eu pra ngm ve
vo excluir esta mensagem na issue qnd vc me adicion ar

**Comment by ashuradev** [comment]
tu viu essa mensagem?
me chamma ai no discord tou com um projeto (n é rede social nem freelancer desta vez kj0dwijrjqwjkkkkk)
preciso deletar meu username daqui desta issue

**Comment by demon-cerbero** [comment]
como vou chamar no discord?


Em seg., 17 de ago. de 2020 às 16:01, Ashura <notifications@github.com>
escreveu:

**Comment by ashuradev** [comment]
me adiciona com meu username ué kkk: ikuzikuyaruhsa#6860
